// For Q1 to Q10:
// Analyze the nested loop architectures and predict the exact output on yourn own;
// do not predict the output pattern by running the code.
// If a question contains multiple choice options, select the correct one.

#include<iostream>
using namespace std;
int main(){
  for (int i = 1; i <= 4; i++){
    for (int j = 4; j >= i; j--){
      cout << "*";
    }
    cout << endl;
  }
}
// 
// Which pattern is generated by this block?
// A. A right-angled triangle pointing downwards (4 stars on top row, decreasing down to 1).
// B. A right-angled triangle pointing upwards (1 star on top row, increasing down to 4).
// C. A square grid containing a total of 16 stars.
// D. A vertically inverted mirror pyramid structure.